name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Load SSH keys
        run: |
          mkdir -p ~/.ssh
          echo "mc.datasektionen.se ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIInRiHxT1rdkn1XDAowiWJqYOJZTqLDrJsCpG/G1zDgh" >> ~/.ssh/known_hosts
          echo "$SSH_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}

      - name: Test
        run: ssh mc@mc.datasektionen.se pwd && find /home -name "docker-compose.yml"

      - name: Run docker compose up
        run: docker compose up -d
        env:
          DOCKER_HOST: 'ssh://mc@mc.datasektionen.se'
